### ISSUE TITLE
Processing deflated CCITT to /CCITT or /JBIG2 "/ Filter /FlateDecode /CCITT" to "Filter/CCITT" or "/Filter /JBIG2"

### ISSUE THREAD

**Issue by maadjordan** [johnwhitington/cpdf-source#161]
To add processing deflated CCITT stream to plain CCITT or add JBIG2 encoding through external files or through (GS)

I've added samples of such files:

[001-022_original.pdf](https://github.com/johnwhitington/cpdf-source/files/3501043/001-022_original.pdf)
[001-022_foxit_phantom.pdf](https://github.com/johnwhitington/cpdf-source/files/3501044/001-022_foxit_phantom.pdf)

**Comment by johnwhitington** [comment]
CCITT to JBIG2 (by calling out to jbig2enc) coming in v2.7, along with lossy image reprocessing. I will let you know when a preview is available. Sample command line:

`cpdf -process-images -convert convert -1bpp-method JBIG2 -jpeg-to-jpeg 65 -lossless-to-jpeg 65`

(`-resample` as an alternative to `-lossless-to-jpeg` also available soon)

Decompressed CCITT to CCITT will be later - I will have to write a CCITT encoder, because I don't want to call out to an external program for that.

**Comment by johnwhitington** [comment]
Since half of this was implemented, and the other half to come, closing.
