### ISSUE TITLE
cpdf -info No longer callable on encrypted PDFs?

### ISSUE THREAD

**Issue by greggarson** [johnwhitington/cpdf-source#182]
Seems in v2.3 these PDFs not respond with an error suggesting the PDF needs to be decrypted 'Failed to decrypt file: wrong password?' in v2.2 cpdf would at least report the encryption status and permissions of the file.  

Not sure if this is a bug or a security update?

**Comment by johnwhitington** [comment]
This is a bug and, as you say, a regression from v2.2.1.

There is a further, deeper, more unusual bug affecting -info, which I had hoped to fix before issuing v2.3.1, but I think I will now produce a new v2.3.1 with just your bug fixed, and leave the other one for a v2.3.2, since your bug is affecting a number of people.

Watch for new executables this week, or early next.

**Comment by greggarson** [comment]
Thanks!
