### ISSUE TITLE
Option to suppress errors on missing pages in a range and process anyway

### ISSUE THREAD

**Issue by psaxena** [johnwhitington/cpdf-source#200]
Hi,

This is more of a query than issue. I want to remove certain pages from a PDF. Currently, i can use command:
`cpdf input.pdf 1-2, 5, 8 -o output.pdf` to get a PDF with selected pages. 

Although, What i am looking for is opposite of that. Is there any command to do that?

Thanks,
Pooja

**Comment by johnwhitington** [comment]
Not presently, but it would be relatively simple to add. We would just allow

NOT3,4,6-8

to remove pages 3,4,6,7,8.

Are you a commercial customer? If so, I can fix this for you today. If not, it will have to go into the next release.

**Comment by psaxena** [comment]
Hi,

Thanks for the update. As of now i am not commercial user. We're exploring cpdf for features and considering to include in our product. Our team may reach out regarding commercial support.

Thanks,
Pooja

**Comment by johnwhitington** [comment]
Thanks. Let me know if you decide to buy, and we can make sure these features are added.

In regard to your second query: there is presently no way to silently ignore pages which are not in the PDF though again, this is easy to add. Alternatively, you can use `cpdf -pages` first to check.

To suppress the error instead of avoiding it, is just a question of scripting. cpdf exits with exit code 2 on error, and prints the message to `stderr`. So you can detect the exit code, and supress the standard error output by redirection.

**Comment by johnwhitington** [comment]
WIsh granted on the NOT inversion of a page range. For example:

`cpdf cpdfmanual.pdf NOTeven -o out.pdf`

is the same as

`cpdf cpdfmanual.pdf odd -o out.pdf`

I need to think a little more about your idea for supressing errors on missing pages. I think maybe we add a `-robust-ranges` option to allow this, rather than making any change in default behaviour.

**Comment by SnowyOw1** [comment]
+1 on this improvement

I have a case of **-range not1** and indeed would like to ignore the error on single-page documents.

As for syntax, may I propose '**_?_**' -- like in regex -- currently not used:

`cpdf -merge input.pdf AND -range 2-end? -stamp-on over.pdf -o output.pdf`
`cpdf input.pdf 1-2, 5?, 8? -o output.pdf`
