### ISSUE TITLE
cpdf text file to pdf and Cyrillic

### ISSUE THREAD

**Issue by grylem** [johnwhitington/cpdf-source#235]
Hi
printf %s\\n проверка >file
cpdf -typeset file -create-pdf-papersize a3portrait -font Helvetica -font-size 10 -o out.pdf
output pdf has weird characters.

Regards
[out.pdf](https://github.com/johnwhitington/cpdf-source/files/7792422/out.pdf)
.

**Comment by johnwhitington** [comment]
The PDF 14 standard fonts used by cpdf cover only the Latin 1 character set. Cpdf uses the PDF encoding WinAnsiEncoding which is almost identical to Latin-1:

https://en.wikipedia.org/wiki/Windows-1252

Cpdf doesn't yet know how to embed other fonts.

However, I am leaving this bug report open, because -typeset should warn about the missing characters, rather than producing garbage.

**Comment by johnwhitington** [comment]
Fixed:

```
cheddar:cpdf-source john$ cpdf -typeset foo -o out.pdf
No glyph for unicode U+043F in this font
No glyph for unicode U+0440 in this font
No glyph for unicode U+043E in this font
No glyph for unicode U+0432 in this font
No glyph for unicode U+0435 in this font
No glyph for unicode U+0440 in this font
No glyph for unicode U+043A in this font
No glyph for unicode U+0430 in this font
```
