### ISSUE TITLE
Bookmarks failed to be recognised

### ISSUE THREAD

**Issue by mkliemann** [johnwhitington/cpdf-source#35]
It seems that the (malformed?) bookmarks generated by the wkhtmltopdf tool/library cannot be handled by cpdf.
cpdf lists no bookmarks for such files, however they show up normally in pdf readers like Adobe Reader.

**Comment by johnwhitington** [comment]
The bookmarks were being read, but excluded from the printout because their destinations did not fall in the specified page range.

I have altered the behaviour to print them all when the page range is the default (all page).

Fixed in forthcoming v2.3

It is, however, still a mystery how Adobe Reader and Preview can make these bookmarks work. I can't see how the destinations are valid at all. Might be remote go to actions.

**Comment by johnwhitington** [comment]
Looks like they are treating an integer in a malformed destination as a page number in the current doucment.. let's see if we can do the same...

**Comment by johnwhitington** [comment]
Fixed in forthcoming v2.3
