### ISSUE TITLE
-scale-contents incorrectly handles link boxes

### ISSUE THREAD

**Issue by LinxiFan** [johnwhitington/cpdf-source#62]
I posted the same issue [here](https://github.com/coherentgraphics/cpdf-binaries/issues/7), but this repo is probably a better place.

After applying -scale-contents option, the original link boxes are not scaled accordingly. As you can see in the screenshot below, the boxes are floating in their original positions:

![image](https://cloud.githubusercontent.com/assets/3018029/12488646/a10462b6-c03a-11e5-93ec-62fcc48cb357.png)

Thanks!

**Comment by johnwhitington** [comment]
This is expected behaviour (that is to say, it's a missing feature, not a simple bug).

If you're an existing or prospective commercial customer, please email me directly and we'll get it fixed. If you're using the not-for-commercial-use version I'm afraid you'll have to wait for the next release, but it is on our list.

**Comment by johnwhitington** [comment]
Fixed in forthcoming v2.3
